### ISSUE TITLE
libn00b Windows port: MSVC-only shims collide with llvm-mingw UCRT (build wall for wax windows-x64)

### ISSUE THREAD

**Issue by meisenbarth** [n00b-lang/n00b#182]
## Summary

The libn00b Windows port (the `feat(windows)` work on main, HEAD `bdd6227d`) was written against **MSVC**'s CRT. The wax `windows-x64` payload cross-builds with **llvm-mingw** (ncc / clang 22.1.8, `ld.lld`, UCRT sysroot), whose CRT already provides many POSIX types/functions MSVC lacks. Result: a **systematic** series of "redefinition / typedef redefinition" errors — every MSVC-only shim collides with the real symbol the UCRT already supplies.

This issue captures the *pattern* and the full findings so it can be fixed in one sweep, rather than one error at a time. It's the current build wall for the wax windows-x64 payload (cep#166).

Related: #180 / PR #181 (the picoquic half of the same pattern — already fixed there).

## How this was found

Iterated the real wax windows-x64 CI build (self-hosted `crayon-windows-1`, llvm-mingw) against a fork with incremental fixes, watching how far the 696-target compile gets each round:

| Round | Fix applied | Reached | Next wall |
|-------|-------------|---------|-----------|
| baseline | — | `[54/696]` | picoquic `wincompat.h:42` `struct timezone` |
| 1 | picoquic timezone guard (PR #181) | `[78/696]` | picoquic `sockloop.c` `EIO` undeclared |
| 2 | picoquic `<errno.h>` (PR #181) | `[101/696]` | libn00b `include/time.h:11` `nanosleep` |
| 3 | libn00b time-shim guards (fork branch below) | **`[144/696]`** | libn00b `n00b.h:46` `pid_t` |

So **picoquic now compiles 100% clean**; the remaining wall is entirely in libn00b's own core/shim headers.

## Confirmed collisions (all the same root cause)

1. **`include/time.h:11` — `nanosleep`** → `error: redefinition of 'nanosleep'`. UCRT provides it (winpthreads). *[fix staged]*
2. **`include/sys/time.h:10` — `struct timezone`** (+ `gettimeofday`) → would collide with UCRT `<time.h>`. Same bug as picoquic's `wincompat.h`. *[fix staged]*
3. **`include/n00b.h:46` — `typedef int pid_t`** (guarded only by `_PID_T_DEFINED`, which llvm-mingw's `sys/types.h` does **not** honor) → `typedef redefinition with different types ('_pid_t' (aka 'long long') vs 'int')`. Hit in `src/core/signals.c`, `mmaps.c`, `init.c`, `src/crt/n00b_crt.c`. ⚠️ Note: UCRT's `pid_t` is `long long`, not `int` — guarding the typedef away on MinGW is necessary but downstream code that assumes `pid_t == int` (e.g. `base_pid_t` at `core/platform.h:479`, format strings) may need a look.

## Queued (spotted, not yet hit)

4. **`include/unistd.h:69` — `usleep`** static-inline shim → likely the same collision (UCRT/winpthreads provides `usleep`). `include/unistd.h` also has ~6 `static inline` shims + ~13 `#define` remaps (`access`→`_access`, etc.) that should be vetted against the UCRT.

## The pattern / the fix

Every case is: an MSVC-only reimplementation guarded by `_WIN32` (or an ineffective `_..._DEFINED` macro) that fires on MinGW too, colliding with the UCRT's real symbol. The mechanical fix is to gate each shim on **`!defined(__MINGW32__)`** so MSVC keeps the shim and MinGW falls through to the CRT.

**But there's a design call to make first** (yours):
- **(a) Support llvm-mingw** — sweep the port's shim headers (`include/time.h`, `include/sys/time.h`, `include/unistd.h`, `include/n00b.h`, and siblings) and guard every MSVC-only definition with `!__MINGW32__`. I've validated the pattern 4 fixes deep; happy to do the full sweep as a PR if that's the intended toolchain.
- **(b) The port targets MSVC** — if llvm-mingw was never the intended Windows toolchain, the wax CI cross-file should point at MSVC instead, and this is moot. (wax CI currently uses llvm-mingw via ncc's `toolchains/windows-x86_64-clang.ini`.)

## Reproduce / starting point

Fork branch **`meisenbarth/n00b:test/windows-mingw-build`** already carries the round-3 fixes (items 1–2 above, guarded `!__MINGW32__`) stacked on the #181 picoquic fixes — a working base to continue the sweep from. The wax side needs no code change beyond repinning `libn00b.wrap`.

cc @baron-crashoverride — this is the libn00b-core half of the wax windows-x64 bring-up; your call on (a) vs (b).

**Comment by meisenbarth** [comment]
Closing — handing the Windows-port toolchain work to @baron-crashoverride to drive. The findings above stand as the map: the [54→144/696] progression, the confirmed collisions (picoquic timezone/EIO, libn00b nanosleep/struct timezone/pid_t), the queued ones (usleep, unistd.h shims), the pid_t-is-`long long` subtlety, and the (a) guard-for-mingw vs (b) target-MSVC decision. Validated fixes live on `meisenbarth/n00b:fix/picoquic-mingw-timezone` (picoquic) if useful as a starting point. Reopen/re-file as you see fit.

**Comment by meisenbarth** [comment]
**Update — empirical answer to the (a)/(b) question: it's (b), and n00b needs NO changes.**

We ran the experiment on a throwaway wax branch (`crashappsec/wax:test/picoquic-mingw-build`): same runner, same ncc, same n00b pin (`bdd6227d`, untouched), but compiling with `--target=x86_64-pc-windows-msvc` (via meson `-Dc_args`/`-Dc_link_args`; ncc forwards unknown flags to clang) inside a VS dev shell (`vswhere` + `Enter-VsDevShell -arch=x64` — clang's MSVC discovery needs it; BuildTools 2022 / MSVC 14.44 detected fine).

| Toolchain | Best result | Failures |
|---|---|---|
| llvm-mingw (windows-gnu) | `[144/696]` after 4 hand-fixes | endless MSVC-only shim collisions (timezone, EIO, nanosleep, pid_t, …) |
| **Clang-MSVC triple** | **`[682/696]`**, `libn00b.a` + picoquic + picotls **compiled and linked** | **zero n00b failures** — only 2 wax-side POSIX-isms left (`sys/wait.h` in the CLI, `realpath` in local_api) |

This confirms what `docs/windows-ncc-shims.md` already implied: the port was written for the Clang-MSVC/UCRT/SDK dialect, and it works as-is under that triple. The mingw collisions this issue cataloged are an artifact of wax CI compiling with bare `CC=ncc.exe`, whose default triple is `x86_64-w64-windows-gnu` because CI builds ncc.exe with the llvm-mingw cross file (`toolchains/windows-x86_64-clang.ini`) — while your local `build-msvc\ncc.exe` defaulted to MSVC. Same build.ps1, opposite triple; `-Db_vscrt=md` was inert on CI all along.

**So the shim sweep proposed above is unnecessary.** The fix is wax-CI-side: pin the triple explicitly (dev shell + `--target=x86_64-pc-windows-msvc`) so the build no longer depends on how ncc.exe happened to be built. Working recipe + the two remaining wax-side fixes live on the wax test branch. PR #181's picoquic patches are also unnecessary under the MSVC triple (wincompat.h behaves as designed there) — closing the loop on why upstream picoquic never saw this.

Runs: mingw wall `31073517411` → MSVC `31075058161` (653/696, one pthread_once user) → `31078910649` (682/696, static libs linked, 2 wax TUs left). cc @baron-crashoverride
